# Generated by Django 3.2 on 2021-04-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name="User's tg id")),
                ('firstname', models.CharField(blank=True, max_length=200, null=True, verbose_name='first name')),
                ('lastname', models.CharField(blank=True, max_length=200, null=True, verbose_name='last name')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='username')),
                ('is_send', models.BooleanField(default=False, verbose_name='is send')),
                ('send_error', models.CharField(blank=True, max_length=5000, null=True, verbose_name='send error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BotUser',
                'verbose_name_plural': 'BotUser',
            },
        ),
    ]
