# Generated by Django 3.2 on 2021-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyRamazonbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='custom_name',
            field=models.CharField(default="Ism o'rnatilmagan", max_length=100, verbose_name='custom username'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='custom_name_change_is_open',
            field=models.BooleanField(default=False, verbose_name='custom name change state'),
        ),
    ]
